### ISSUE TITLE
Fix some stale texts

### ISSUE THREAD

**Issue by erights** [Agoric/SES-shim#103]
The actual error string at https://github.com/Agoric/harden/blob/0a5185ee224b98e75623a2f88143d118e0849eaa/src/anonIntrinsics.js#L230 

`'GeneratorFunction.__proto__ was not Function.prototype.constructor'`

is actually wrong here. This one should be `AsyncGeneratorFunction`. No doubt a copy-paste error.

Also the comment at
https://github.com/Agoric/harden/blob/0a5185ee224b98e75623a2f88143d118e0849eaa/src/anonIntrinsics.js#L179
should be updated not to refer to Caja.

**Comment by jfparadis** [comment]
@erights, in SES 2.0, the tes has been made more robust, and the message made closer to the specs:

```js
  // Use Function.prototype.constructor in case Function has been tamed
  assert(
    getPrototypeOf(AsyncGeneratorFunction) === FunctionPrototypeConstructor,
    'AsyncGeneratorFunction.__proto__ should be Function',
  );
```

![Screen Shot 2020-02-28 at 10 49 14 AM](https://user-images.githubusercontent.com/2583204/75578047-fdfa2c00-5a17-11ea-8a03-b5da33f74680.png)

**Comment by jfparadis** [comment]
Comment updated.
