### ISSUE TITLE
Allow inner to view and update json provided by outer

### ISSUE THREAD

**Issue by ashconnell** [Agoric/SES-shim#107]
I'm trying to determine whether SES is suitable to allow running scripts provided by third-party users that control their individual Objects in a WebXR app.

Essentially, the "host" application has a 3D Scene (using ThreeJS) which calls an update function each frame (~60fps) to update Objects in the Scene. Some of these Objects are run by third-party scripts. Each time the update function runs we would want to call the third-party script with just the data for their Object and allow them to view and modify it as they see fit.

My current understanding of SES is that I would need to evaluate the Scene's Object every frame to make it safe and then call the third party script with the safe version. My concern in doing this is that running evaluate on many Objects, many times per second is probably not going to be performant.

Am i potentially missing something here that would allow this to work without constant evaluation? Eg:

```js
// adding an object to the scene run by a third-party script
function addObject(properties, scriptSrc) {
  const object = new SceneObject(properties)
  object.script = s.evaluate(scriptSrc)
  scene.add(object)
}

// called ~60 times per second
function update() {
  scene.objects.forEach(object => {
    // call the evaluated third-party script
    // passes in the object properties and allows the script to modify as they see fit
    object.script.update(object.properties)
  })
}
```

**Comment by jfparadis** [comment]
@ashconnell, sorry for the delay in answering. We are finalizing a new SES which is simpler and more performant.

Overall, evaluation is not the only way to safely put code in contact with each other. I will try to understand your use case:
- You can evaluate and therefore isolate each third-party script in its own Compartment.
- In your example, your evaluation returns a function (`s.evaluate(scriptSrc)`) and you just need to call that function later on, and you don't need to re-evaluate afterwards.
- Once the code has been evaluated, it basically executes at native speed.
- It looks like you have the perfect case, the scripts are pure transformational libraries (they only rely on input and outputs). If your input arguments to the functions are primitives, or if you prevent their mutability with `harden()`, and if you are careful with the return values (no live references) then you are very close to complete isolation.

I hope this helps. Feel free to ask for more details. I will keep this open.

**Comment by kriskowal** [comment]
Thank you @ashconnell. Please reopen if you have any follow-up questions!
