### ISSUE TITLE
createSES.js wrongly assumes that JSON is a subset of JavaScript

### ISSUE THREAD

**Issue by erights** [Agoric/SES-shim#115]
At
https://github.com/Agoric/SES/blob/acd8b151ff3ae450d5a6933fe09dac01ca87dbbc/src/bundle/createSES.js#L111
createSES.js wrongly assumes that JSON is a subset of JavaScript, and so can form a valid JavaScript program including the whitelist by splicing in a `JSON.stringify` of the whitelist.

This is why the suggestion at https://github.com/Agoric/SES/pull/134#discussion_r318261361 did not work.

This bad assumption is widespread, including on tc39. I had not noticed it before either. See https://github.com/tc39/ecma262/issues/1681

**Comment by jfparadis** [comment]
Closing, this is no longer necessary:
- Shims were required by SES to cross realm boundaries. Serialization was necessary. This is no longer the case.
- The whitelist was including Symbols and other non JSON objects/primitives. This is also no longer the case.
Closing.
