### ISSUE TITLE
We need better dependency diagnostic for too-old node versions

### ISSUE THREAD

**Issue by dckc** [Agoric/SES-shim#125]
I just heard about release 5. I tried to follow the getting started docs to the letter; I'm losing.

```
connolly@jambox:/tmp/ses-5$ node ex.js 
/tmp/ses-5/ex.js:8
]
^

SyntaxError: Unexpected token ]
```

After fixing that typo (#114) I get:

```
connolly@jambox:/tmp/ses-5$ node ex.js 
/tmp/ses-5/node_modules/ses/dist/ses.cjs.js:403
  async function* aStrictAsyncGenerator() {} // eslint-disable-line no-empty-function
                ^

SyntaxError: Unexpected token *
```

Is my node too old?

```
connolly@jambox:/tmp/ses-5$ node --version
v8.14.0
```

If so, I think you can use some sort of `engine` thingy in your package.json to tell me what version(s) of node you support.

full transcript of my session: https://gist.github.com/dckc/e7bd1571c3c17110eab7110f4e319194

**Comment by kriskowal** [comment]
Tracking on #22.
