### ISSUE TITLE
SES should be split into proposal and shim repositories

### ISSUE THREAD

**Issue by erights** [Agoric/SES-shim#129]
I have now renamed tc39/proposal-frozen-realms to tc39/proposal-ses , as discussed at tc39. We should move SES documentation there, update or remove stale documentation there, and rename this repository to emphasize that what remains is just the ses-shim. We should parallel exactly the split we just did between proposal-realms and realms-shim.

**Comment by jfparadis** [comment]
This was done a while back:
- Proposal: https://github.com/tc39/proposal-ses
- Shim (this repo): https://github.com/Agoric/SES-shim/issues/129

Closing, complete.
