### ISSUE TITLE
rename this repo to `ses-shim` ?

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#13]
We're planning to retire https://github.com/Agoric/SES , in favor of this repo. Obviously we need to remove the `-beta` from the name. @erights @dtribble any objections to naming it `https://github.com/Agoric/ses-shim` ?

(note that we've used that name for this repo in the past, before renaming it to SES-beta, so if you visit that URL, you'll be redirected back here)

**Comment by erights** [comment]
Once it is ready for others to use for production, yes, I think it should be renamed `ses-shim`. Since we're already using the name `SES-beta` to signal unreadiness, I think we should not rename until then.

**Comment by warner** [comment]
Ah, good point. To unblock the swingset-on-new-SES effort (https://github.com/Agoric/agoric-sdk/issues/477), we need to publish new SES to NPM, but that doesn't mean the repository itself has to be named anything other than `SES-beta`.

The NPM release will probaby be named `SES-0.7.0`. The last old-SES release (made just today) was `SES-0.6.5`. We can reserve the 0.6.x numberspace for old-SES, and deliver 0.7.x or 0.x (x >= 7) until we're ready to declare it 1.0.

**Comment by jfparadis** [comment]
Great.
1. I like `ses-shim`: it is the SES repo as in `git clone <something>ses-shim.git`
2. I like the `npm` package `ses`. It is also the `ses` path in the monorepo `./packages/ses`
That was the intention to avoid confusion between the two.

Let's do this for version:
- This SES is too big of a change to be called a minor release and `0.8.0` doesn't cut it. It's a complete API change, and a minor just doesn't capture that. We need to abide to the semantic:
> Changes that break backward compatibility: Major release
https://docs.npmjs.com/about-semantic-versioning
- Remove `-beta` from the git repo and add it to the version: `1.0.0-beta.0`. The semantic of npm versioning allow for a `prerelease`. The .0 indicates the first beta. When we have a new beta, we increment the .0 to .1 and so on.
https://docs.npmjs.com/cli/dist-tag
- The readme will capture the npm version and display it (it is configures to show the current version)

This is a very good read:
https://medium.com/@kevinkreuzer/publishing-a-beta-or-alpha-version-to-npm-46035b630dd7

**Comment by michaelfig** [comment]
Maybe we can keep the `-beta` in the git repo name for now, but still use something like `2.0.0-beta.0` for the NPM version?

**Comment by dtribble** [comment]
Thanks for the pointer. I really like having "beta" et al in the version name. With real support for that, it seems way more clear about what the state is, which is more important for ses than many other packages. 

Version 1 non-beta will still be a shim, though, correct? In terms of the base package name, when Compartments are directly supported, would users change what they are importing?  i.e would they go from importing `ses-shim`, which gets them a bunch of shimming behavior to importing `ses` which expects to merely configure existing primitives? What's been the package naming across other transitions from "shimmed" to "no shim needed"?

**Comment by erights** [comment]
First, agree that with the `-beta` in the version name we do not need it in the repository name. Good.

> when Compartments are directly supported, would users change what they are importing?

Once `Realm`, `lockdown`, and `Compartment` are actually standard, adopted, and deployed by the platform, we won't import then at all anymore. We'll just find them starting from the standard global object, just like `Date`.

**Comment by kriskowal** [comment]
This transition appears to be completed.
