### ISSUE TITLE
Membrane proxy

### ISSUE THREAD

**Issue by mappum** [Agoric/SES-shim#131]
I've been digging into SES as we plan to build on it, so right now I'm thinking about safe endowments/data passing between SES Realms, and I have a few questions for you to make sure I'm thinking about it the right way.

As I understand it, your "harden" function is enough to prevent SES-realm-confined untrusted code from modifying prototypes accessed via outer-realm objects. But it does NOT harden values returned by outer-realm functions, and so without wrapping functions to return hardened values there would be a confinement escape route. Is this correct?

Couldn't there be a simple catch-all way to harden all data that passes through the membrane into an SES realm using proxies? I started an implementation for this here: https://github.com/mappum/potr/blob/master/index.js This approach hardens the data by recursively proxy-wrapping all accesses, erroring on all attempted modifications, and wrapping functions to protect their return values as well. Are there any issues with this approach, or does it not prevent all confinement escapes? (Assume it is being used by calling `protect` inside the SES realm for all endowments passed in, plus all function arguments passed in by outer-realm calls.)

**Comment by kriskowal** [comment]
Please reopen or open a follow-up issue if there is material from this conversation we would like to capture in documentation. Thanks!
