### ISSUE TITLE
On Firefox - TypeError: property "input" is non-configurable and can't be deleted

### ISSUE THREAD

**Issue by katelynsills** [Agoric/SES-shim#139]
Our integration tests our failing on Firefox 66.0.2 with the error "TypeError: property "input" is non-configurable and can't be deleted". 

It looks like this fails around the test for RegExp.compile. Is this related to RegExp.input? If so, how would we like to handle it?
![Screen Shot 2019-03-28 at 1 16 17 PM](https://user-images.githubusercontent.com/2441069/55190413-fe7da900-515c-11e9-93d7-e56eab30e5c0.png)

**Comment by jfparadis** [comment]
The SES 2.0 taming of RegExp handles the removal of the non-configurable static members like `RegExp.compile` and `RegExp.input` by creating a new constructor:
https://github.com/Agoric/SES-shim/blob/master/packages/tame-global-regexp-object/src/main.js#L17

It is tested here:
https://github.com/Agoric/SES-shim/blob/master/packages/tame-global-regexp-object/test/tameGlobalRegExpObject.test.js#L16

Closing, case covered.
