### ISSUE TITLE
nondeterminism: remove *.toLocaleString ?

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#149]
If this changes behavior according to something outside the process, we need to remove it, or remap it to e.g. `Object.prototype.toString`.

There is an `Object.prototype.toLocaleString`, but according to [the spec](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-object.prototype.tolocalestring) it exists purely as a fallback for other objects that don't override it (and it just delegates to the plain `.toString()` method on `this`).

But for other primordial objects, we need to check that their individual `toLocaleString` method doesn't cause nondeterminism. This includes `Number`, `Array`, and `Date`, at the very least.

**Comment by kriskowal** [comment]
@erights has released changes that redirect the locale methods of strings to the corresponding non-locale-oriented method.
