### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by katelynsills** [Agoric/SES-shim#161]
> I would love to have typescript typings for this, as it makes learning a new project (and using it correctly) much easier

From Agoric/SES#64

**Comment by tobowers** [comment]
When I try to do a `import {lockdown} from 'ses'` I get: `Cannot find module 'ses'.` is that expected? Same file seems to work with `node -r esm` (same code that I would expect to work in typescript).

**Comment by kriskowal** [comment]
> When I try to do a `import {lockdown} from 'ses'` I get: `Cannot find module 'ses'.` is that expected? Same file seems to work with `node -r esm` (same code that I would expect to work in typescript).

@tobowers Very sorry for missing this message. The API today is `import 'ses'` which introduces a globalThis.lockdown.
