### ISSUE TITLE
is it safe to share a WeakMap of already-frozen objects?

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#165]
This weakmap seems to be global mutable state. Why is that ok in this case?

Also, is it shared between realms? Between calls to require('harden')?

_Originally posted by @dckc in https://github.com/Agoric/SES/issues/4#issuecomment-464727318_

**Comment by kriskowal** [comment]
This discussion appears to have run its course. Please reopen if there is need for further discussion.
