### ISSUE TITLE
build intermediate bundle at runtime?

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#170]
To inject the `SES` object into new SES realms (this allows each realm to create child realms, to arbitrary depths), we need a string that defines SES. We build this out of the contents of the `src/bundle/` directory by running `npm run-script build-intermediate`, which writes the generated string into `src/stringifiedBundle`. The top-level `src/index.js` reads this string as a module and passes the string object into the SES constructor.

As a result, we must regenerate this bundle after making any changes to `src/bundle/*.js`. Our `npm test` script does this automatically (to avoid confusion), but we have to remember to check this new bundle into git after each change.

(This is a subset of the `npm run-script build` script that generates the `dist/ses-shim.js` file, which can be included as an HTML `<script>` tag, and adds a `SES` object to the global environment. This is useful for web environments but not so much for Node.js applications.)

It might be nice to generate the intermediate bundle at runtime, rather than ahead-of-time. Our `build-intermediate` script uses `rollup` for this job, which could be done inside `index.js` instead of as a separate step. One problem I don't know how to solve yet is that `rollup` wants to run asynchronously, whereas all module exports need to be available by the time the module finishes being evaluated. If rollup has a synchronous mode, this could simplify our workflow a bit.

**Comment by kriskowal** [comment]
SES lockdown, compartment, and realms being now decoupled, this issue appears to be obsolete. Please reopen if this issue requires attention.
