### ISSUE TITLE
SES.confine() throws away stack traces and line numbers

### ISSUE THREAD

**Issue by dckc** [Agoric/SES-shim#172]
In Agoric/SES#9, @warner writes Aug 9:
> Another thing to keep in mind is debuggability and sourcemaps. At present, each SES.confine() is a barrier beyond which stack traces and line numbers get thrown away. It might be interesting to ...

he goes on to discuss solutions, but meanwhile, I think it's worth promoting the problem to its own issue.

**Comment by kriskowal** [comment]
SES now carries sourceURL and has taming options for errors. Please reopen if this issue is still relevant.
