### ISSUE TITLE
Constant endowments optimization not working

### ISSUE THREAD

**Issue by XmiliaH** [Agoric/SES-shim#18]
Constant endowments will be seen as undefined.
```JS
const Marker = "Marker";
new Evaluator().evaluate("bad", Object.create(null, {bad: {value: Marker}}))===undefined // true
```
but this should be true
```JS
const Marker = "Marker";
new Evaluator().evaluate("bad", Object.create(null, {bad: {value: Marker}}))===Marker // false
```
like non constant endowments
```JS
const Marker = "Marker";
new Evaluator().evaluate("bad", {bad: Marker})===Marker // true
```

The problem seems to be https://github.com/Agoric/evaluator-shim/blob/master/src/optimizer.js#L150, since `this` is the safe global and does not contain the endowments.

**Comment by kriskowal** [comment]
`Evaluator` has become `Compartment`, `evaluate` no longer accepts per-evaluation endowments, and endowments are captured on `compartment.globalThis`, so a lot has changed for these cases.

Today, this works:

```js
import "ses.js";
lockdown();
const Marker = "Marker";
console.log(new Compartment(Object.create(null, {bad: {value: Marker, enumerable: true}})).evaluate("bad")===Marker) // true
```

I assume this is consistent with the spirit of this issue and will close. Please reopen if problems persist.
