### ISSUE TITLE
SES on wasm

### ISSUE THREAD

**Issue by dckc** [Agoric/SES-shim#182]
@dtribble suggested using XS, but since it throws away the source code of functions, I can't imagine it will work. I looked at otto and its successor https://github.com/dop251/goja , but it's not quite clear how to get started with those.

So I tried https://duktape.org/ , written in C. Compiling it to webasm was entirely straightforward:

After [installing emcc](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html
):

```
# How does this thing normally compile?
~/projects/duktape-2.3.0$ make -f Makefile.cmdline 
gcc -o duk  -Os -pedantic -std=c99 -Wall -fstrict-aliasing -fomit-frame-pointer -I./examples/cmdline -I./src    -DDUK_CMDLINE_PRINTALERT_SUPPORT -I./extras/print-alert -DDUK_CMDLINE_CONSOLE_SUPPORT -I./extras/console -DDUK_CMDLINE_LOGGING_SUPPORT -I./extras/logging -DDUK_CMDLINE_MODULE_SUPPORT -I./extras/module-duktape src/duktape.c examples/cmdline/duk_cmdline.c extras/print-alert/duk_print_alert.c extras/console/duk_console.c extras/logging/duk_logging.c extras/module-duktape/duk_module_duktape.c -lm

# Let's throw out a few options and feed the rest to emcc...
connolly@jambox:~/projects/duktape-2.3.0$ emcc -s WASM=1 -o duk.html -I./examples/cmdline -I./src    -DDUK_CMDLINE_PRINTALERT_SUPPORT -I./extras/print-alert -DDUK_CMDLINE_CONSOLE_SUPPORT -I./extras/console -DDUK_CMDLINE_LOGGING_SUPPORT -I./extras/logging -DDUK_CMDLINE_MODULE_SUPPORT -I./extras/module-duktape src/duktape.c examples/cmdline/duk_cmdline.c extras/print-alert/duk_print_alert.c extras/console/duk_console.c extras/logging/duk_logging.c extras/module-duktape/duk_module_duktape.c -lm
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/home/connolly/.emscripten_cache/is_vanilla.txt" for subsequent builds)
...
connolly@jambox:~/projects/duktape-2.3.0$ firefox duk.html
```

And voila, a js repl in webasm running in firefox.

According to https://duktape.org/guide.html , const has function scope and there's no support for ES6 modules. But they talk about hooking babel into their module support... maybe it could make up the difference? The TCB is starting to get uncomfortably large at that point, I suppose.

**Comment by kriskowal** [comment]
This conversation appears to be concluded. Please reopen if there is need for further discussion.
