### ISSUE TITLE
SES on moddable's XS

### ISSUE THREAD

**Issue by dckc** [Agoric/SES-shim#184]
I followed the [Getting Started][1] docs; got the dev tools built and the hello world app running

cc @dtribble @erights 

[1]: https://github.com/dckc/moddable/blob/public/documentation/Moddable%20SDK%20%E2%80%93%20Getting%20Started.md

2018-09-30 04:04 PM      moddable        9b53f14 boilerplate

**Comment by kriskowal** [comment]
My current understanding is that we won’t use SES-shim on XS, as-is. An Agoric runtime on XS will need some parts of SES like `harden`, but not `lockdown`. We will need to build CommonJS and run-time ESM support out of SES parts too, but won’t use the SES `Compartment`. We will need to tool to precompile ESM in Agoric application archives.

I would like to continue tracking that project on #400. Please reopen here if this conversation is in fact ongoing.
