### ISSUE TITLE
publish on NPM

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#193]
We should get this up on npm, under the name `SES`.

@kriskowal, does this seem worthy of claiming the `ses` name on npm? I see that you've got an old snapshot of Caja published under that name right now (last updated about four years ago).

@jfparadis, this repo incorporates the Realms shim by using a git submodule (which is currently a week or two out of date). Would it make more sense to get Realms into NPM too? Then SES could just have a dependency on some version of Realms. Actually, it would be both a regular dependency and a `devDependency`, because we must stringify+flatten the whole Realms constructor to build the SES shim string. (We'd probably need to pin the version in both, to avoid allowing downstream users to get one form of Realm on their top-level SES environment, and a different version for new Realms built inside that one).

cc @erights

**Comment by kriskowal** [comment]
Yes, I believe SES should be published as ses on npm. I believe you
and @erights are already owners and can publish. There isn’t enough usage
on the project to worry about semantic versioning, but the last published
version is <1.0.0 so you can bump the minor version number without
interfering with any prior users.
