### ISSUE TITLE
Assert Function.__proto__ identity across all compartments

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#200]
@erights asked to verify the identity of `Function.__proto__` in the new SES: are the prototypes of the safe and unsafe function always equal?

Overall: yes, the original value remains the same, is unchanged, although its `contructor` property is set to a different value. 

In more details:
- In the start compartment, `Function.__proto__` of the unsafe function is altered but isn't set to a different value (it is read-only). The taming process only changes its constructor property. `Function.prototype` isn't modified, and remains equal to `Function.__proto__`.

- In a compartment, `Function.__proto__ `of the newly created safe Function is set to `Function.prototype` by the normal creation of a new function. There is no special setup required, all functions created in the realm inherit from `Function.prototype`. The safe function `prototype` property is changed, and set to the intrinsic `FunctionPrototype`.

The process for the other function constructor is different.

**Comment by jfparadis** [comment]
@erights, closing, I hope that the explanation is satisfactory.

**Comment by erights** [comment]
Oh yes, it is good. Sorry, I didn't know you were waiting for a response.

**Comment by jfparadis** [comment]
Sorry, I did close without asking first.
