### ISSUE TITLE
Reconnect the challenge demo

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#203]
The Agoric SES challenge is now offline. It was based on the version SES that was built on realms and used the realm shim, and therefore not relevant anymore.

The Agoric SES challenge has been ported to the new SES but is still not connected (available publicly on HTTP).

Because of the transition from rawgit to github pages, we cannot use rawgit, but @warner mentions that github pages could interfere with the Agoric documentation which is also served as github pages.

FYI: @warner

**Comment by warner** [comment]
@kriskowal has an idea for this involving something named `zeit`?

**Comment by kriskowal** [comment]
Aye. I suspect the demo could be made to work with gh-pages, but https://zeit.co/ can publish a PR to a staging URL which I found very useful.
