### ISSUE TITLE
Document limitation: `evaluate` leaks scopeProxy as `this`

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#21]
Referencing https://github.com/tc39/proposal-realms/issues/173 from @erights:

See related https://github.com/tc39/proposal-realms/issues/171 https://github.com/tc39/proposal-realms/issues/172

All the own property names on the safeGlobal that are non-configurable, non-writable data properties are candidates for including in the optimizer's list of optimized variable name lookups. These names are looked up on the scopeProxy before the normal call to direct eval.

If the user could somehow install an accessor property that is looked up during this lookup, the getter might dereference a free variable "eval". This might trigger the scopeHander's "provide unsafeEval the first time" logic, enabling unsafeEval to be captured by that free variable lookup.

**Comment by kriskowal** [comment]
Closing as duplicate of https://github.com/Agoric/evaluator-shim/issues/4
