### ISSUE TITLE
[Best Practice] when to run lockdown ?

### ISSUE THREAD

**Issue by GrandSchtroumpf** [Agoric/SES-shim#215]
Hello,
I'm implementing ses in an online IDE with a plugin system currently working with iframes (https://remix.ethereum.org/). Each plugin is managed by an instance of a class. 
As far as I understand I should have one `Compartment` per plugin. But should I run `lockdown()` once in the application or once per plugin (in the constructor of the class for example) ?

Also, is there a way to stop "evaluate" ? I tried to delete the instance of the compartment but I can still exchange event messages. 

Here is a sample : 
```typescript
import { lockdown } from 'ses'
class SesPlugin {
  constructor() {
    lockdown()  // One lockdown() per plugin ????
  }
  activate() {
    this.compartment =  new Compartment({
      host: harden({
        send: (message) => this.getMessage(message),
        on: (cb) => this.postMessage = cb
      })
    })
    this.compartment.evaluate(pluginCode) // plugin run host.on() to listen on host message
    this.postMessage('hello')
  }
  deactivate() {
    delete this.compartment
    this.postMessage('goodbye') // this message is sent to plugin while I would expect it not too...
  }
  getMessage(message) { /* handle messages from plugin code */ }
}
```

**Comment by erights** [comment]
> But should I run lockdown() once in the application or once per plugin (in the constructor of the class for example) ?

You should run `lockdown` only once, and as early as possible. After `lockdown` you are now running under SES rules, where safety is much easier to think about. The code that called lockdown continues after the call with the same global. We refer to this as the "start compartment", and it still contains host objects providing the dangerous authority to the application as a whole. This start code should then create other compartments and subdivide and attenuate this initial authority, giving each compartment no more authority than it needs and should have. As you say, each plugin would be in a separate compartment. The code running within these compartments are running in a world that is already SES-safe, and so have no need to call lockdown.

**Comment by erights** [comment]
```js
delete this.compartment;
```

simply removes the property named `"compartment"` from your `this` object. It has no effect on that compartment nor on the code running in the compartment. Termination is an interesting topic which we'll expand on another time.

**Comment by kriskowal** [comment]
Thank you for your question. Please reopen if we can elaborate.
