### ISSUE TITLE
Disable comment parsing

### ISSUE THREAD

**Issue by mpetrunic** [Agoric/SES-shim#234]
It seems like it tries to parse comments and fails.
```
Build success: 'build/index.js' bundled as 'dist/bundle.js'!
Snap evaluation error: possible import expression rejected around line 8527
```

![image](https://user-images.githubusercontent.com/8836210/76961551-d9f68000-691d-11ea-9e72-78c7c025a6a2.png)

**Comment by erights** [comment]
Hi @mpetrunic, thanks for raising this!

In response I filed related bug https://github.com/Agoric/SES-shim/issues/235 which explains why this is, in most ways, working as intended. But it also says that we should introduce options to suppress the check you're running into above, and two other checks like it. Hence the new issue asking for those options.

**Comment by kriskowal** [comment]
Thank you. Tracking on #235. Please reopen if that answer is not satisfying.
