### ISSUE TITLE
ses-0.7.4 NPM tarball doesn't match source tree

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#236]
I compared the contents of the `ses-0.7.4` tarball on NPM, obtained with:

```
$ mkdir t
$ cd t 
$ yarn add ses@0.7.4
$ ls node_modules/ses/dist/*
```

against the dist files created from the source repo:

```
$ git clone https://github.com/Agoric/SES-shim
$ cd SES-shim
$ git checkout SES-v0.7.4
  # 'git log' should show we're at e35ea71
$ yarn
$ yarn build
$ ls packages/ses/dist/*
```

and they look different. Diffing `ses.cjs` looks like the published version lacks the additions made in 4e784ed (to `ses/enablements`, for `ErrorPrototype.toString` and `TypeErrorPrototype`):

```
$ diff -u -B4 SES-shim/packages/ses/dist/ses.cjs t/node_modules/ses/dist/ses.cjs
--- SES-shim/packages/ses/dist/ses.cjs	2020-03-20 16:12:26.537188641 -0700
+++ t/node_modules/ses/dist/ses.cjs	2020-03-18 13:00:44.288000000 -0700
@@ -2872,14 +2872,8 @@
   ErrorPrototype: {
     constructor: t, // set by "fast-json-patch"
     message: t,
     name: t, // set by "precond"
-    toString: t, // set by "bluebird"
-  },
-
-  TypeErrorPrototype: {
-    constructor: t, // set by "readable-stream"
-    name: t, // set by "readable-stream"
   },

   PromisePrototype: {
     constructor: t, // set by "core-js"
```

It looks like maybe `yarn build` was not run before the `yarn publish`, and we got a set of `dist/` files that came from an earlier commit (the files match 186f6f15 and a few commits before that, which means it includes PR #231 but not #227).

I don't know yarn well enough to know if we need to set up `package.json` to automatically run `yarn build` before generating the tarball (in our pre-yarn era, I had script entries like `publish: npm build && npm pack && npm publish`), or if yarn is supposed to automatically do that and something else is going on.

**Comment by kriskowal** [comment]
In https://github.com/Agoric/SES-shim/commit/f38669a696fa53d2ff5b47a482b12635c06be610, I republished 0.7.4 as 0.7.5 and added a prepublish script to ensure a clean and fresh build for each release.

We’ll be needing to rewrite the release instructions, best practices, and repository scaffolds in light of our learnings about hybrid module system packages. We should take note to include this prepublish script.
