### ISSUE TITLE
Throw when undeniables are not found on the intrinsics?

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#24]
Customizing a realm by removing intrinsic could clash with the behavior of the evaluator.  For example, removing `Array` will not prevent the evaluator from creating array instances `[]`.

Many object remain accessible by grammar (we call them the "undeniable" objects) even when globals are being removed.

Should the shim (and the specs) warn against that situation, or should it remain silent (as it is the case with `iframes`).

**Comment by kriskowal** [comment]
Aside: do we need to document *maximal* supported engine versions? Future language versions can introduce additional undeniables that would immediately become mutable shared state that lockdown does not address?

**Comment by erights** [comment]
Good idea! Yes.

**Comment by kriskowal** [comment]
Closing as stale. No longer applies to the lockdown + Compartment model.
