### ISSUE TITLE
delete spurious tags from repo

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#249]
At some point, it looks like this repo acquired copies of all the old (unscoped) tags from the original solorepos. We've got good+scoped tags like `SES-v0.5.0`, but we also have bad+unscoped tags like `0.5.0`.

The chore is to identify and delete all of these tags. The command to run is `git push origin :0.5.0`, for all tags that we identify as spurious.  These will be the tags without a projectname+hyphen prefix. All of the spurious tags should point to commits for which there is also a non-spurious tag, and it might be good to check that before deleting.

**Comment by warner** [comment]
Oh also, after we delete these from the github repo, all contributors should check their local trees and delete them there too, to reduce the chances of these tags getting pushed back up again in the future. I think there are options/flavors for a bare `git push` to push all tags, in addition to branch heads, and I suspect it's one of these that caused those unscoped tags to show up on github.

**Comment by warner** [comment]
I've deleted these tags from the github repo. @kriskowal @erights @michaelfig @jfparadis please run the following commands locally to remove them from your own machines:

```
for t in `git tag |grep '^0'`; do git tag -d $t; done
for t in `git tag |grep '^v0'`; do git tag -d $t; done
for t in `git tag |grep '^v1'`; do git tag -d $t; done
for t in `git tag |grep '^v2'`; do git tag -d $t; done
```

**Comment by michaelfig** [comment]
I think `git fetch origin --prune --prune-tags` will work if your version of git supports it.

**Comment by warner** [comment]
These are gone from github, if I see them pop up again I'll figure out who to hassle about leftovers in their local trees.
