### ISSUE TITLE
Create a `bleach` repair

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#25]
Referencing https://github.com/tc39/proposal-realms/issues/115

Currently, the confinement of the evaluator depends on shadowing all existing unsafe globals by effectively defining a variable of the same name with value `undefined`. This is done dynamically via the `with()` on a `Proxy()`.

This adequately meets `typeof` but fails to throw a `Reference Error` when a variable declaration is omitted, violating one of the security objectives of "strict mode" which is to guard against accidental globals.

One mitigation is to "bleach" the unsafe global (remove all properties) after all code has run in the primal root realm and control has passed to the primal compartment. This should be done, like all other repairs to the environment, via a separate library.

@erights

**Comment by kriskowal** [comment]
This no longer fits our model of a powerful start compartment and powerless + endowments for child compartments.
