### ISSUE TITLE
compatibility: setting Error.prepareStackTrace results in an error

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES-shim#251]
the popular [`express`](https://github.com/expressjs/express) (15.5m/week)
has a dependency [`depd`](https://github.com/dougwilson/nodejs-depd) (16m/week) used for creating deprecation messages.
`depd` uses [some weird voodoo](https://github.com/dougwilson/nodejs-depd/blob/4e1ba5a1dbecb6a949f4c41976cf0080c38352b5/index.js#L381-L399) to get v8's object version of the stack by temporarily overriding `Error.prepareStackTrace`.

There is discussion of making setting this field to fail silently, instead of loudly. `depd`'s implementation **will not work gracefully** under a silent failure of setting .

**Comment by warner** [comment]
I'm running into this now too, as `cosmic-swingset` uses `express`. This pattern has appeared in a couple of libraries so far:

* [`callsite`](https://www.npmjs.com/package/callsite), used by [`better-assert`](https://www.npmjs.com/package/better-assert)
* [`stack-trace`](https://www.npmjs.com/package/stack-trace), used by [`insist`](https://www.npmjs.com/package/insist)
* [`bindings`](https://www.npmjs.com/package/bindings) (popular: 6m/week, used directly by 2k other packages, including LMDB which we use in cosmic-swingset)

**Comment by kumavis** [comment]
also seeing it a lot around tooling for loading native modules, like [`bindings`](https://github.com/TooTallNate/node-bindings) and [`node-gyp-build`](https://github.com/prebuild/node-gyp-build)

**Comment by warner** [comment]
The most immediate consequence of this for me is that `tape` tests, when they fail, cannot tell me which assertion failed: it wants to use this Error fiddling to build a stack trace to the assertion, and instead I get a stack trace to the internal code where the Error fiddling failed. I can work around it by making sure my unit tests always pass (which means doing a lot of `console.log`s).

**Comment by erights** [comment]
@kumavis @warner 
Now that #359 is merged, could you check if we still have the errors? If not, please close. Thanks.

**Comment by erights** [comment]
> Now that #359 is merged, could you check if we still have the errors? If not, please close. Thanks.

Closing. Please reopen if this is still a problem.
