### ISSUE TITLE
Document minimum platform support for ses-shim

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES-shim#252]
Would be nice to have a clearly documented minimum platform support versions (may differ from dev tools / build system requirements)

I currently use node v10
node v12 is the current latest LTS
https://github.com/nodejs/Release#release-schedule

one potential issue to wider platform support is `get-anonymous-intrinsics` use of
```js
new RegExp()[SymbolMatchAll]();
````
https://github.com/Agoric/SES-shim/blob/7e69a42086154d91fe0d58406cd4fa83c437e971/packages/ses/src/get-anonymous-intrinsics.js#L35

here is my quick-and-dirty monkey patch to re-add node v10 support (also used babel' plugin to convert import -> commonjs)
https://github.com/kumavis/cytoplasm/commit/d928d43f66d21c4847ac30028114c5193658ab05

**Comment by erights** [comment]
Hi @kumavis do you need support earlier than v12?

If we agree on v12, what is needed? Could you extract just the changes needed for that into a SES-shim PR? Thanks.

**Comment by kumavis** [comment]
I don't think support for earlier than v12 is really reasonable due to the release schedule
so nothing is needed, except documenting and testing the supported versions

**Comment by kriskowal** [comment]
Tracking on #22. Thank you.
