### ISSUE TITLE
rework endowments and transforms, add globalLexicals option

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#256]
(trying to capture what I learned from @michaelfig today and @erights earlier, please correct my misunderstandings)

## terminology

"Endowments" are defined specifically to mean properties present on the global object. These cannot be easily denied to arbitrary evaluated code (which can compute a property name and then look it up on `globalThis`): denial requires either solving the halting problem or running the code in a simulator. Each endowment may or may not be frozen. The global object itself may or may not be frozen. If the global object is not frozen, then code evaluated in a compartment might add/modify/remove endowments.

A different thing, tentatively named "globalLexicals", are names that are visible in the global lexical scope but are not properties on the global object. These *are* fairly easy to deny to evaluated code: simply parse the code and reject it if there are any unbound references to the denied name (this is used by e.g. the SwingSet metering code, to allow transform-injected code to reference a meter object, while denying the original user-level code from reaching it). The objects themselves might be mutable or immutable, but the overall set of Global Lexicals is effectively immutable: the only way to add a missing one is to assign to an unbound name, and that's forbidden by strict mode, and shadowing an existing one will only affect the scope of the shadowing variable.

## old SES

In old SES, the `endowments` argument was used by the scope Proxy to handle lookups of otherwise unknown names. This put them somewhere between proper globals and global lexicals.

## new SES (currently)

Current SES provides four places where endowment-like things might be provided:

* `new Compartment(endowments, ..)`
* `new Compartment(.., { transforms })`
* `c.evaluate(src, { endowments })`
* `c.evaluate(src, { transforms })`

Both sets of transforms are defined as lists of objects with `.rewrite()` methods, which both accept and return a `{ src, endowments }` object. This lets transforms modify the endowments as they modify the source code.

The `endowments` passed into the Compartment constructor are (I think) merged with those passed as an option to `c.evaluate`.

## proposal

If I remember @michaelfig 's advice correctly, the proposal is to remove `endowments` from everything except the Compartment constructor, and to add a new option that allows control over the global lexicals (on the whole compartment only). As a side-effect, transforms no longer need to interact with anything but source code. And transforms will be defined as properties of the Compartment, not options of an evaluation. So the remaining API will be something like:

* `new Compartment(endowments, { globalLexicals, transforms })`
* `c.evaluate(src)`

and `transforms` will be defined as a list of functions, each of which accepts a `src` string and returns a new `src` string. The `c.evaluate` call will no longer take endowments or transforms as options. I *think* this also means moving the remaining `sloppyGlobalsMode` option from `c.evaluate` to `new Compartment`, but I'm less sure of that.

## implementation

I believe the new global lexicals will be implemented by adding these names to the "optimizer string", along with the primordials that are not being overridden by endowments.

Changing `transforms` is mostly a matter of tracking down the separate `globalTransforms` and `localTransforms` removing the latter.

This is probably related to #19 .

**Comment by kriskowal** [comment]
I suspect we will need to differentiate endowments and transforms that **must** be inherited by child compartments from those that **must not**.

**Comment by warner** [comment]
From yesterday's meeting, I think we concluded that enforcing transforms would be done by users applying a library function to modify the `c.Compartment` object in the new compartment:

```js
import { enforceTransforms } from 'compartment-utils';
const c = new Compartment({ transforms });
enforceTransforms(c, transforms);
c.import(moduleSubjectToTransform)
```

As a user, that sounds slightly less convenient than having something built-in to the API, but I think it would work, and I'm all in favor of simplifying the API.

We're probably on the hook for writing that library function too, but it wouldn't be part of the core API.

**Comment by kriskowal** [comment]
A more recent consensus is that we will not add an API for injecting global lexicals, and will instead lean on `compartment.evaluate` to introduce variables to the “global contour”. We will need to add tests and likely add behaviors to the compartment global proxy. Tracking with #322.

We still agree to remove the threading of endowments from the translators, which I’ll track with #321.

This issue is no longer tracking work and can be closed as a duplicate or aggregate of these finer granularity issues or kept open to track the overall epic, at @warner’s discretion.
