### ISSUE TITLE
Construct Compartment bundler

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#296]
After #295, we then need the ability to capture all of the sources that would need to load to execute a particular entry module for an application and construct a bundle containing all of those module. The bundle must then be importable in another environment with compartments.

This might be tentatively called `sessify` since it resembles `browserify`.

This change may motivate the creation of a Compartment `load` method in addition to the `module` method, so that an assembled compartment graph can be induced to call `importHook` for every module in a working set without executing any of them.

**Comment by erights** [comment]
> This might be tentatively called sessify since it resembles browserify.

This collides with MetaMask's use of "sesify" for similar things, named for the same reason.

https://medium.com/metamask/metamask-monthly-january-cd969e6e20f9

**Comment by kriskowal** [comment]
Tracking on #336
