### ISSUE TITLE
Rename ModuleStaticRecord

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#299]
The 262 specification and Compartments proposals have two types name `StaticModuleRecord` and `TextStaticModuleRecord` (verify). The former probably ought to be reserved for the general interface and the latter the name of a constructor. I don’t find either name particularly ergonomic, but regardless, `ModuleStaticRecord` needs to be renamed. I would, though I’m sure there will be objection, like to name this `Module` given its primacy and relationship to `Function`. The terms “module” and “static” at least need to be reversed.

**Comment by erights** [comment]
>  though I’m sure there will be objection, like to name this Module given its primacy and relationship to Function. 

You got that right. Please don't ;)
