### ISSUE TITLE
Expose SES API as globals

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#301]
Currently we export `lockdown`. `Compartment` gets introduced as a side-effect of `lockdown`, but should exist before. We arrived at a consensus that `harden` should be exposed as a global. The current notion is that `harden` should only exist after lockdown, or maybe exist but throw before lockdown, to avoid the hastle that anything hardened before lockdown would need to 
somehow be promoted to actually-hard after lockdown.

**Comment by erights** [comment]
I hadn't considered before the possibility that `harden` before `lockdown()` exists but throws. I like it.
