### ISSUE TITLE
expose c.globalThis, not c.global?

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#313]
During this week's meeting, I noticed some latent confusion about how each `Compartment` object exposes the global object of the compartment it represents. For ocap security, it's important to freeze this object (as well as anything added to the global lexical scope), to deny an ambient communication channel between unrelated objects within.

Currently, the compartment exposes a property named `.global` on the `Compartment` object. We use this in e.g. agoric-sdk `import-bundle` like this:

```js
const c = new Compartment(endowments, options);
harden(c.global);
c.evaluate(confinedCode);
```

In the meeting, I heard multiple people say that the property was actually named `.globalThis`. Or at least that it ought to be named that. Looking at the implementation, it looks like it really is named `.global`:

https://github.com/Agoric/SES-shim/blob/e54c237300405f7c4fd1b0b10d80f1b7c2ef6c3a/packages/ses/src/compartment-shim.js#L148-L150

So this ticket is to decide on what the name ought to be, and change the implementation to match. I'll update `import-bundle` after the subsequent release.

Incidentally, since we're expanding the set of global-ish things and trying to decide how to name them all, I want to verify my assumption: we *can* freeze/harden every object that is ambiently available to all code inside the compartment, right? I think the requirement is that we pre-harden anything we add to the as-yet-ambiguously-named non-enumerable "global lexical scope", add other non-hardened-yet things to `endowments` where they'll be copied onto the enumerable global, create the Compartment, maybe add some more things to `c.globalThis`, and then finally `harden(c.globalThis)` (which will recursively harden `endowments` and subsequent additions to `c.globalThis`, but not the global-lexicals). And only then is it safe to `c.evaluate` or `c.import`.

Right?

**Comment by kriskowal** [comment]
The name should be `globalThis`. I have a change in progress.
