### ISSUE TITLE
Lift @agoric/assert

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#324]
The `@agoric/assert` package is currently published from the `agoric-sdk` repository. As we would like to take a dependency upon `assert` in `ses`, and use it to carry more complete exception metadata, we should move it down the layer cake.

This change will not address other standing issues with its API or the need for a `guard` package as mentioned by @dtribble offline.

**Comment by erights** [comment]
See #440

**Comment by kriskowal** [comment]
@erights addressed this by moving the core of `@agoric/assert` into the SES shim proper.
