### ISSUE TITLE
tame x.toLocale functions?

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#335]
I was reading through the docs for [String.prototype.toLocaleLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase), and noticed that its zero-argument behavior depends upon the host's default locale. In addition, the one- and array- argument behavior depends upon which locales are installed (the spec says it will choose the "best available" locale out of the list supplied).

I think there are other functions in the SES approved list that have similar behaviors. If I look at everything that mentions "Locale", I see:

* `Object.prototype.toLocale`
* `Number.prototype.toLocaleString`
* `BigInt.prototype.toLocaleString`
* `Date.prototype.toLocaleString`, `.toLocaleDateString`, and `.toLocaleTimeString`
* `String.prototype.localeCompare`, `.toLocaleLowerCase`, and `.toLocaleUpperCase`
* `Array.prototype.toLocaleString` (also for various TypedArrays)

I haven't tested this yet, but I see all those functions are approved, so I'm concerned that they'll expose nondeterminism to the SES environment.

Did we have an answer for this? I think we talked about defining SES as living in a world with a single fixed locale (maybe the `C` locale?), but I don't see anything obvious in the shim that might impose this.

**Comment by erights** [comment]
Remind me please? What is the `C` locale? Is there a helpful link?

**Comment by warner** [comment]
I haven't seen any canonical docs on it, I've just noticed that a lot of linux systems have their `$LOCALE` environment variable set to `C`, and I've seen unit tests that explicitly set it to the same when they want the results to be consistent and not particularly internationalized.

This seems useful: https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do/87763#87763

**Comment by erights** [comment]
All these `*[Ll]ocale*` methods have now been removed from the whitelist. Closing.

**Comment by erights** [comment]
Reopening because #378
