### ISSUE TITLE
update NEWS with properties removed in SES-0.9.0

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#379]
As part of #335 , the 0.9.0 release removed several locale-related properties from the SES primordials. We should enumerate those changes and add them to the NEWS file (even though the 0.9.0 tarball is frozen, it would still be helpful to investigate things like #378 if the current trunk's `NEWS.md` included the list).

Based upon the diff, I *think* the list is:

* `Object.prototype.toLocaleString`
* `Number.prototype.toLocaleString`
* `BigInt.prototype.toLocaleString`
* `Date.prototype.toLocaleDateString`
* `Date.prototype.toLocaleString`
* `Date.prototype.toLocaleTimeString`
* `String.prototype.localeCompare`
* `String.prototype.toLocaleLowerCase`
* `String.prototype.toLocaleUpperCase`,
* `Array.prototype.toLocaleString`
* `%TypedArray%.prototype.toLocaleString`

@erights could you confirm? If so, I'll make the patch.

**Comment by erights** [comment]
Confirmed
