### ISSUE TITLE
Tests left running even after all launching terminals closed

### ISSUE THREAD

**Issue by erights** [Agoric/SES-shim#388]
My mac laptop's fan was running very loud. Investigating, I found 6 node processes, each using over 99% of CPU. I closed everything down, including Terminal, VSCode, and all browsers. Those six processes still running hard.

Attached are some screenshots illustrating the situation. The interesting one is node-command-lines, which looks like something our tests would spawn.

It is possible it is my bug, since I've been developing on my own branch which has gone through many broken states. Nevertheless, I'd expect all these to terminate when I close the Terminal.

![node-command-lines](https://user-images.githubusercontent.com/273868/87860747-cde2f500-c8f4-11ea-9949-4efe0428c45f.png)
![activity-monitor](https://user-images.githubusercontent.com/273868/87860749-d3403f80-c8f4-11ea-80fd-9ca4dcbce534.png)
![open-files-ports](https://user-images.githubusercontent.com/273868/87860753-ddfad480-c8f4-11ea-9560-3bced14056e1.png)
![stats](https://user-images.githubusercontent.com/273868/87860759-e4894c00-c8f4-11ea-9099-42bd144a41c7.png)
![memory](https://user-images.githubusercontent.com/273868/87860761-e81cd300-c8f4-11ea-90f4-3b35e50f27fa.png)

**Comment by warner** [comment]
Hrm, I know `tap` spawns multiple child processes (one per test file) in parallel, to speed up tests. It sounds like one of them got left behind and didn't know when to stop.

I've seen `tap` get confused when I interrupted it (control-C / SIGINT), it feels like the parent process terminates, but the children keep running. Their stdout should be routed to a pipe that dies with the parent process, but their stderr might just flow through to the initial shell. The result is a lot of noise for a few minutes until the test processes wind down.

I wonder if one of those test processes observed an error while trying to write to the now-closed stdout pipe, and it's reaction was to try to write even more to stdout. That would lead to an infinite series of errors.

**Comment by kriskowal** [comment]
This is likely a defect in `tap`. I would like to archive this until we see it again and can build a case for an issue on `tap`.
