### ISSUE TITLE
deps: is Lerna necessary? 

### ISSUE THREAD

**Issue by SMotaal** [Agoric/SES-shim#4]
Amazing to finally see SES broken down into monorepo-style packages BTW 👍

So I'd like to play devil's advocate here, is lerna needed?

Obviously there is some need for it to close the yarn-npm gaps, but I also want to consider that being not the case in this current structure.

- [ ] Discuss this further 😄

**Comment by jfparadis** [comment]
Lerna is currrently necessary for fine-tuning the parallelization of jobs, something Yarn 1.x doesn't do properly. For example, Lerna has a "no bail" option to control whether or not commands running in packages are stopping the entire process.

See:
https://classic.yarnpkg.com/blog/2017/08/02/introducing-workspaces/#integrating-with-lerna

**Comment by kriskowal** [comment]
I would entertain a PR that removes a dependency on Lerna and retains support for the existing scripts’ behaviors, but I also intend to figure out over time how to better make use of Lerna. I still am early in my learning journey for this part of the stack and haven’t yet learned enough to rely on it for conventional commit messages and release management.

This is not an issue I intend to track for now, so closing, but please consider continued discussion open.
