### ISSUE TITLE
can/should lockdown() be called twice?

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#40]
While experimenting with SwingSet unit tests, where I have not yet moved to `tap` (which runs each test in a separate process), I figured I should see what happens if `lockdown()` is called multiple times in the same process (which would happen all the time under `tape`, which runs all tests in a single process). It fails:

```js
import { lockdown } from './src/ses.esm.js';
console.log('lockdown 0');
lockdown();
console.log('lockdown 1');
lockdown();
console.log('lockdown 2');
```

yields:

```
lockdown 0
Removing intrinsics.AsyncFunction.toString
Removing intrinsics.AsyncGeneratorFunction.toString
Removing intrinsics.Atomics
Removing intrinsics.FunctionPrototype.arguments
Removing intrinsics.FunctionPrototype.caller
Removing intrinsics.Generator.@@toStringTag
Removing intrinsics.GeneratorFunction.toString
Removing intrinsics.SharedArrayBuffer
Removing intrinsics.SharedArrayBufferPrototype
Removing intrinsics.FunctionPrototypeConstructor.toString
Removing intrinsics.Compartment.toString
Removing intrinsics.CompartmentPrototype.toString
lockdown 1
/home/warner/bindmounts/trees/agoric-sdk/node_modules/esm/esm.js:1
const __global__ = this;(function (require, module, __shared__) { var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,function(){return e}},r(r.s=2)})([(function(e,t){var r;t=e.exports=$,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Number.MAX_SAFE_INTEGER

[TypeError: Cannot assign to read only property 'now' of function 'function Date() {
    if (new.target === undefined) {
      // We were not called as a constructor
      // thi...<omitted>... }']
```

I'd be totally happy with being told "don't do that", but it might be nice if the second attempt threw a "clear don't do that" error.

We might allow the second attempt exit silently, but if the options passed into each `lockdown()` call are different, that would raise confusion as to what environment you wound up with, so maybe a clear error would be best.

This is using the shim built from version e5035fd5f84eaed55d2249d4fd8e402b2e87ac5c.

**Comment by jfparadis** [comment]
I think that the problem should be phrased like this:

> Calling `lockdown()` creates a transition from JS to SES, but when called from SES, what should `lockdown()` do?

On one hand, `lockdown()` means to emulate XS, and on that engine, runtime begins in either mode, and there is no transition (assumption, needs to be verified).

For other engines, at one point we thought that SES could be a pragma like strict mode. If that is still correct, I think throwing would violate developer's expectations. If you are is JS strict mode and invoke strict mode, JS doesn't throw:

```js

const isStrict = (function() { return !this; })();
console.log(isStrict);
(0,eval)(`
	"use strict";
	const isStrict = (function() { return !this; })();
	console.log(isStrict);
	(0,eval)(\`
		"use strict";
		const isStrict = (function() { return !this; })();
		console.log(isStrict);
	\`);
`);
```
Output:
```
false
true 
true
```

If we ever think that SES will be a pragma, I think throwing would violate developer's expectations. Here is my proposal:
1. Ignore SES to SES transitions
2. Throw on attempt to go from a downgraded SES to another SES (aka lockdown was initally called with optional parameters), and we can't make any assumptions and guarantees.

@erights

**Comment by warner** [comment]
I'm tempted to ask for the first invocation to remember the options it got, and then silently ignore a transition to the same set of options (downgraded SES to identically-downgraded SES), because there's a batch of SwingSet tests which build a whole series of swingset kernels in a row (to test persistence and resuming from the old states), which would be hard to break up into separate processes. But I want the final API to be as safe as possible, and I can work around the test issue by jumping ahead to the next phase of swingset-on-ses2 (have the caller be responsible for setting up the SES environment, rather than the swingset code).

**Comment by jfparadis** [comment]
Very interesting. 

Is that a test issue? Maybe the tests are missing a clear distinction between AAA (arrange, act, assert)? Maybe callable fixtures are required? Maybe tests do and should not depend on each other?

Alternatively, if your goal is to clearly do something else, maybe you can have your own temporary wrapper to lockdown instead of pushing that concern up the dependency chain?

**Comment by jfparadis** [comment]
Fixed.
