### ISSUE TITLE
Shipping SES without Babel

### ISSUE THREAD

**Issue by rekmarks** [Agoric/SES-shim#449]
As the maintainers are no doubt aware, [`@agoric/babel-standalone`](https://www.npmjs.com/package/@agoric/babel-standalone) constitutes more than 90% of the [`ses`](https://www.npmjs.com/package/ses) bundle size:
- https://bundlephobia.com/result?p=ses@0.10.2 **(1.6mb minified)**
- https://bundlephobia.com/result?p=@agoric/babel-standalone@7.9.5 **(1.5mb minified)**

The `@babel/standalone` fork seems to only be used for the `StaticModuleRecord` functionality, which in turn appears to be used to support module imports inside compartments. Not all uses of `ses` require imports, however, and it would be great to be able to have `lockdown` and `Compartment` without the weight of `@agoric/babel-standalone`.

Would it be possible to ship a version of `ses` without `@agoric/babel-standalone`?

**Comment by kriskowal** [comment]
Yes! Version 0.10.0 creates a thin `ses/lockdown` layer that brings the weight back down to about 34KB minified, and `dist/lockdown.min.js` captures that rollup. Version 0.10.3 is slated to bring `Compartment.evaluate` back into the thin layer, by splitting the Compartment definition between `ses/lockdown` and the `ses` shim with module support #443.

Thank you for bringing this up.

**Comment by rekmarks** [comment]
Oh, fantastic! Thank you @kriskowal. I'll await that release, feel free to close 😄
