### ISSUE TITLE
Suggestion: add `assert.string` to the assert package

### ISSUE THREAD

**Issue by FUDCo** [Agoric/SES-shim#450]
(Filing here per @erights request since the `assert` package is apparently migrating to this repo).

I just got done rewriting a bunch of what-we-decided-were-inappropriate type coercions into type checking asserts (long story), and after the tedium thought to check our usage, and it turns out that outside of tests of the assert package itself, all but 3 occurrences of `assert.typeof` in Agoric SDK are `assert.typeof(thing, 'string')`.  I'm wondering if a small ergonomics improvement might be to add an `assert.string(thing)` (or maybe `assert.isString(thing)`) function to the assert API.

**Comment by erights** [comment]
Done.
