### ISSUE TITLE
lockdown - assigning Symbol.match to RegExp instance

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES-shim#460]
per MDN you should be able to assign `Symbol.match` to a `RegExp` instance
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/match

```js
'use strict'

require('ses') // version 0.10.3
lockdown({ errorTaming: 'unsafe' })

var regex = /a/;
regex[Symbol.match] = false;
```
results in error

```
/home/xyz/Development/es-abstract/zzz.js:11
regex[Symbol.match] = false;
                    ^

[TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot assign to read only property 'Symbol(Symbol.match)' of object '[object RegExp]'
  at Object.<anonymous> (/home/xyz/Development/es-abstract/zzz.js:11:21)
  at Module._compile (internal/modules/cjs/loader.js:1158:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
  at Module.load (internal/modules/cjs/loader.js:1002:32)
  at Function.Module._load (internal/modules/cjs/loader.js:901:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
  at internal/main/run_main_module.js:18:47]
```

**Comment by erights** [comment]
Is this an override mistake issue? Should add `RegExp.prototype[Symbol.match]` to the enablements whitelist?

**Comment by erights** [comment]
What code is doing this? If it is code you control and it is the override mistake, you can always avoid the override mistake by using `defineProperty` rather than assignment.

**Comment by kumavis** [comment]
looking deeper into this, i think ses is currently doing the right thing
I saw some code modifying this and thought it was a part of the api intended to be modified, but looks like it was part of a shim test that was intentionally messing with the environment
