### ISSUE TITLE
Consolidate rather than duplicate common configuration policies

### ISSUE THREAD

**Issue by erights** [Agoric/SES-shim#465]
See https://github.com/Agoric/SES-shim/pull/447#discussion_r481530131 where @kriskowal suggests for a change to `.prettierrc.json` 
> This is a change we can and should apply to the entire repository, perhaps piecemeal and then holistically.

Between our main monorepos (SES-shim and agoric-sdk) there are many such duplicated policy files, or almost duplicated policy files with *unintended* drift apart. This is a maintenance headache.

**Comment by erights** [comment]
@kriskowal I take it that this is what your `scripts/repackage.sh` is designed to do. So can I assign this to you?

**Comment by kriskowal** [comment]
I believe we’ve taken this as far as necessary for the purposes of lint, prettier, and jsconfig.json. We can continue to evolve `scripts/repackage.sh` as is helpful going forward.
