### ISSUE TITLE
"ses-lite" missing permit for %InertStaticModuleRecord%

### ISSUE THREAD

**Issue by rekmarks** [Agoric/SES-shim#467]
Using `ses@0.10.3`, I call `require('ses/dist/lockdown.cjs')` and then `lockdown()`. The following error is thrown:

```
Uncaught Error: Expected permit object at whitelist.%InertStaticModuleRecord%
  at Object.completePrototypes (...)
  at repairIntrinsics (...)
  at assign.lockdown (...)
```

If I remove the line `    '%InertStaticModuleRecord%': InertStaticModuleRecord,` from the `intrinsics` object inside `ses/dist/lockdown.cjs`, the error no longer occurs and everything appears to work, although the following messages appear in the console:

<details>
<summary>Toggle console message visibility</summary>
<pre>
<code>Removing intrinsics.Promise.any
Removing intrinsics.%InertFunction%.arguments
Removing intrinsics.%InertFunction%.caller
Removing intrinsics.%InertGeneratorFunction%.arguments
Removing intrinsics.%InertGeneratorFunction%.caller
Removing intrinsics.%InertAsyncFunction%.arguments
Removing intrinsics.%InertAsyncFunction%.caller
Removing intrinsics.%InertAsyncGeneratorFunction%.arguments
Removing intrinsics.%InertAsyncGeneratorFunction%.caller
Removing intrinsics.%InitialDate%.arguments
Removing intrinsics.%InitialDate%.caller
Removing intrinsics.%SharedDate%.arguments
Removing intrinsics.%SharedDate%.caller
Removing intrinsics.%InitialError%.arguments
Removing intrinsics.%InitialError%.caller
Removing intrinsics.%SharedError%.arguments
Removing intrinsics.%SharedError%.caller
Removing intrinsics.%InitialRegExp%.arguments
Removing intrinsics.%InitialRegExp%.caller
Removing intrinsics.%SharedRegExp%.arguments
Removing intrinsics.%SharedRegExp%.caller
Removing intrinsics.%InertCompartment%.arguments
Removing intrinsics.%InertCompartment%.caller
Removing intrinsics.%StringPrototype%.replaceAll</code>
</pre>
</details>

My execution environment is a Web Worker using the latest version of Google Chrome. The error is not thrown if I `require('ses')` using `ses@0.10.3` or `ses@0.9.1`.

**Comment by erights** [comment]
Only sloppy functions have `caller` and `arguments` properties. Is `ses/dist/lockdown.cjs` sloppy?

**Comment by erights** [comment]
Nevermind my question. Doesn't fit the symptoms. Will investigate tomorrow.

**Comment by kriskowal** [comment]
I’ve been able to reproduce this error with this script in Chrome 85.

```html
<!doctype html>
<script src="dist/lockdown.umd.js"></script>
<script>
  lockdown({
    errorTaming: "unsafe"
  });
</script>
```

I’ve also reproduced it separately in a web worker, but that appears to not be germane.

**Comment by erights** [comment]
Core problem diagnosed, but with some remaining mysteries.

We recently divided the whitelist into `whitelist` which applies to ses-without modules, and `moduleWhitelist` with the additional elements to be added to `whitelist` when doing ses-with-modules. Loading just lockdown runs ses-without-modules. The non-module whitelist doesn't have `%InertStaticModuleRecord%`. But the intrinsics do. `completePrototypes` goes through the intrinsics, looking up their entry in the whitelist, to figure out how to do its thing (add in the appropriate prototype objects). `%InertStaticModuleRecord%` is in the intrinsics it starts with.

No idea yet why this fails on the web but works on Node. So far, the bug seems like it should be host-independent.

**Comment by kriskowal** [comment]
Reproduced on Node.js with:

```js
// node index.cjs
require("./dist/lockdown.cjs");
lockdown({
  errorTaming: "unsafe"
});
```

And with Node.js targetting ESM:

```js
// node index.js
import "./lockdown.js";
lockdown({
  errorTaming: "unsafe"
});
```

It looks like all of the tests that import SES-lite are failing to actually call `lockdown()`. They did not call `lockdown()` before splitting the lite layer, at least in the immediate prior version.
