### ISSUE TITLE
Should we stop suppressing the override mistake for `Function.prototype.apply`?

### ISSUE THREAD

**Issue by erights** [Agoric/SES-shim#474]
At https://github.com/Agoric/SES-shim/blob/9a7a0975036d8d938263ba265f747876d7d91599/packages/ses/src/enablements.js#L67 we say that we added `Function.prototype.apply` to the enablements whitelist because of tape.

At https://github.com/Agoric/SES-shim/pull/473#issuecomment-697887937 @ljharb says that tape does not do an overriding assign to `apply`. If `tape` is no longer a problem, or if we were mistaken about whether it was a problem in the first place, and if we do not encounter any other such problems, we should remove `Function.prototype.apply` from the enablements whitelist.

**Comment by ljharb** [comment]
As far as I can discern, tape has never done an assignment to apply.
