### ISSUE TITLE
Annoying display of `Object <[Object: null prototype] {}>`

### ISSUE THREAD

**Issue by michaelfig** [Agoric/SES-shim#477]
@erights, @kriskowal:

Is there any particular reason why https://github.com/Agoric/SES-shim/blob/54e0b0c910fd19bec14f9e3ff9e556f17f952fd4/packages/ses/src/whitelist.js#L504 effectively forces `Object.prototype.__proto__ = null`?

This just makes printing of objects under SES extremely annoying (displays `Object <[Object: null prototype] {}> { ... }` under Node.js instead of just `{ ... }`).

Shouldn't we instead have?
```js
  '%ObjectPrototype%': {
    // 19.1.3 Properties of the Object Prototype Object
    '[[Proto]]': '%ObjectPrototype%',
```

**Comment by erights** [comment]
The alternative you show is an inheritance cycle, where `Object.prototype.__proto__ === Object.prototype`. Fortunately, this isn't even possible in JavaScript.

Other than the `Object.prototype` object itself, what other objects should inherit for `Object.prototype` that are instead inheriting from `null`?

**Comment by michaelfig** [comment]
Here is the behaviour that annoys me:

```js
import 'ses';
console.log({});
lockdown();
console.log({});
```

I get the following:
```sh
node -r esm foo.js
{}
Object <[Object: null prototype] {}> {}
```

**Comment by erights** [comment]
I agree that is a problem. I've noticed that too. We need to diagnose what's causing it. I think the explanation lies elsewhere, but I do not understand it and have not experimented.

**Comment by erights** [comment]
This is waiting for us to find and fix where something in agoric-sdk associated with xsnap is overriding a constructor property by assignment. Only when that's fixed can we stop tuning `Object.prototype.constructor` into an accessor and fix this bug.
