### ISSUE TITLE
"SourceType" should not be used to version the transforms

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#48]
Currently, the transform creates the equivalent of a static record, with `sourceType` member:
https://github.com/Agoric/transform-module/blob/master/src/index.js#L87

This is needs to be equal to "module", "script", or "expression":
https://github.com/Agoric/transform-module/blob/master/src/index.js#L211
https://github.com/Agoric/transform-module/blob/master/src/index.js#L224

And is wired to derive which transforms to enable:
https://github.com/Agoric/transform-module/blob/master/src/babelPlugin.js#L469
 
In other words, `sourceType` is really about the type of the source. 

However, changes in Babel or in how our Babel plugin work could introduce incompatible changes that need to be detected by the consumers. If `sourceType` is used, then we would need to include then we would need to include three versions for every change, "module-v2", "script-v3", AND "expression-v3" because changes will most likely impact all three types at the same time. 

It would be much better to keep version orthogonal to type, so a new version affects all types at the same time.

@michaelfig, following our discussion today, does this clarifies my position?

@erights @warner

**Comment by kriskowal** [comment]
@michaelfig Do you believe that this issue remains relevant? Can you frame this as an action item?

**Comment by michaelfig** [comment]
No longer relevant.
