### ISSUE TITLE
Math.random undefined in compartment

### ISSUE THREAD

**Issue by EtDu** [Agoric/SES-shim#491]
```
> lockdown({ mathTaming: "unsafe" })
true
> Math.random
[Function: random] Function <Function <[Object: null prototype] {}>>
> const comp = new Compartment()
undefined
> comp
Compartment {}
> comp.evaluate("Math.random()")
Thrown:
TypeError <Object <Object <[Object: null prototype] {}>>>: Math.random is not a function

```

**Comment by kumavis** [comment]
this is using a build of ses off of master d41b004feaf0925832b90a816afcc97415e46bbe

**Comment by EtDu** [comment]
Same result is achieved without `mathTaming`

**Comment by kumavis** [comment]
reproduced on 89294755245b0c558c8cf6423f66a1a48ec7f905

**Comment by kriskowal** [comment]
cc @erights I’m fuzzy on the design principles here but the observed behavior might be consistent with the design.

I believe the design principle is:

> Child compartments are powerless unless so endowed, by default, regardless of the taming rules. The taming rules apply to the start compartment only.

That’s one that fits in my head anyway. There are probably nuances. I hope we arrive at something easy to grok at the end of the day.

It should be possible to work-around this regardless by endowing the compartment with the `Math` from the start compartment.

**Comment by erights** [comment]
@kriskowal 's diagnosis is correct. What happens if you change the Compartment construction call to
```js
const comp = new Compartment({ Math });
```
?

**Comment by EtDu** [comment]
@erights that works!

**Comment by kumavis** [comment]
so this is understood and resolved now, but was confusing so it should be clearly documented somewhere

**Comment by kriskowal** [comment]
Agreed. Please review the writing on https://github.com/Agoric/SES-shim/pull/494.
