### ISSUE TITLE
Test SES on XS

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#540]
- [ ] Emulate Compartment Mapper filesystem `read` power on XS.
- [ ] Run Node.js style module resolution on XS
- [ ] Emulate Ava

To bootstrap on XS, we have two paths. We can embed the compartment mapper as ESM in an XS binary, or create an XS bootstrap that accepts the compartment mapper etc as a Rollup bundle as an XS resource and evaluate it.

**Comment by dckc** [comment]
I just made https://github.com/agoric-labs/moddable/tree/text-utf8-enc-dec is moddable public current (9b2399f) plus just TextEncoder / decoder: 558da14

@kriskowal you might use this to be sure the parsing issue you're seeing is not due to us using an outdated branch.

**Comment by kriskowal** [comment]
We’ve elected to go a different direction. In agoric-sdk, we have xsnap. We may revisit this by putting together something like test262 verification of a valid SES environment but that work is not planned.
