### ISSUE TITLE
CHANGES? Release notes? SECURITY.md outdated

### ISSUE THREAD

**Issue by dckc** [Agoric/SES-shim#567]
While filing an issue (https://github.com/Agoric/agoric-sdk/issues/2263 ) to update agoric-sdk to the Jan 21 v0.11.1 release, the issue template prompted me to comment on security issues.

So I went looking for SES-shim release notes. I don't see any. I don't see a CHANGES file.

SECURITY.md still shows 0.6.x as the current supported version.

**Comment by dckc** [comment]
https://github.com/Agoric/SES-shim/blob/master/packages/ses/NEWS.md is the CHANGES / release notes , @kriskowal tells me.

**Comment by erights** [comment]
Yup. Updated
