### ISSUE TITLE
Something about xsnap not compat with SES 0.12.1

### ISSUE THREAD

**Issue by erights** [Agoric/SES-shim#570]
See CI failure at https://github.com/Agoric/agoric-sdk/pull/2323/checks?check_run_id=1819852110 . A relevant part seems to be

```
  Error {
    message: 'Uncaught exception in v1: SyntaxError: ^((?:.*[( ])?)[:/\\w-_] invalid range',
  }

  › runToIdle (packages/xsnap/src/xsnap.js:126:15)
```

**Comment by erights** [comment]
Since #571 claims to fix a bug that doesn't happen for me locally, and only happens to https://github.com/Agoric/agoric-sdk/pull/2323 under CI, how can we test #571 without making a new SES release and switching https://github.com/Agoric/agoric-sdk/pull/2323 to depend on that newer release instead? Or is this indeed the lowest friction way to test #571 ?

**Comment by dckc** [comment]
I built a test to verify that xsnap loses on the former regex. I stashed it but didn't check it in.

I can make a test for the fixed regex...

**Comment by dckc** [comment]
The tests below verify the fixed regex.

You can also do it with the repl:

```
~/projects/agoric/agoric-sdk/packages/xsnap$ ./src/xsrepl
xs> const FILENAME_FILTER = /^((?:.*[( ])?)[:/\w_-]*\/(packages\/.+)$/;
```


adding these to the branch for https://github.com/Agoric/agoric-sdk/pull/2266 is a bit lazy, but...

reject non-std range
https://github.com/Agoric/agoric-sdk/commit/9f2ac658fe0240cdd4b9ac10facf7089dde96db5

accept std range
https://github.com/Agoric/agoric-sdk/commit/8967b0e78f239662d403c0ed9b736e10fd96457c

**Comment by dckc** [comment]
This episode suggests bumping up the priority of #508 .
