### ISSUE TITLE
Error.stackTraceLimit cannot be set, makes popular libraries fail

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#8]
I'm working on getting SwingSet to run on the new SES shim. One problem I've run into so far:

```js
const { lockdown } = require("./src/ses.cjs.js");

lockdown();

async function fail() {
  throw Error("oops");
}

async function run() {
  let dropped = fail();
  // let a rejected Promise fall out of scope, to trigger Node's
  // `emitUnhandledRejectionWarning` message
}
run();
```

which fails with:

```
$ node t.js 
Removing intrinsics.AsyncFunction.toString
Removing intrinsics.AsyncGeneratorFunction.toString
Removing intrinsics.Atomics
Removing intrinsics.FunctionPrototype.arguments
Removing intrinsics.FunctionPrototype.caller
Removing intrinsics.Generator.@@toStringTag
Removing intrinsics.GeneratorFunction.toString
Removing intrinsics.SharedArrayBuffer
Removing intrinsics.SharedArrayBufferPrototype
Removing intrinsics.FunctionPrototypeConstructor.toString
Removing intrinsics.Compartment.toString
Removing intrinsics.CompartmentPrototype.toString
internal/process/promises.js:223
  Error.stackTraceLimit = 0;
                        ^

[TypeError: Cannot add property stackTraceLimit, object is not extensible]
```

It looks like Node's unhandled-rejection handler is trying to get an Error object without a stack, and to do that it thinks it can modify `Error.stackTraceLimit` "temporarily":

https://github.com/nodejs/node/blob/bbab963db80528f3f932269774f1d5d6012fbb68/lib/internal/process/promises.js#L229-L232

```js
function getErrorWithoutStack(name, message) {
  // Reset the stack to prevent any overhead.
  const tmp = Error.stackTraceLimit;
  Error.stackTraceLimit = 0;
  // eslint-disable-next-line no-restricted-syntax
  const err = new Error(message);
  Error.stackTraceLimit = tmp;
  ObjectDefineProperty(err, 'name', {
    value: name,
    enumerable: false,
    writable: true,
    configurable: true,
  });
  return err;
}
```

I can't immediately think of a workaround.. maybe replace their unhandled-rejection handler with our own? Meticulously avoid leaving any broken Promises lying around? Shim `Promise` to attach a rejection handler to otherwise-unhandled ones to avoid triggering the global handler?

**Comment by warner** [comment]
Oh, it looks like `node --unhandled-rejections=none` is one option (ignore them, which isn't great for debugging).

The default setting causes the handler to delegate to user-controllable code (it does `process.emit('unhandledRejection', ..)` and if that returns `true`, it doesn't invoke the code that causes a problem). So another option is something like this:

```js
process.on('unhandledRejection', (error, p) => {
  console.log('unhandled rejection, boo');
  console.log('error is', error.toString());
  return true;
});
```

**Comment by erights** [comment]
Attn @bmeck

**Comment by erights** [comment]
We could add an option to the Error repair so that, before freezing the exposed safe `Error` constructor, we first do:

```js
defineProperty(Error, 'stackTraceLimit', {
  get() { return 0; },
  set(_) { /* ignore silently */ },
});
```

**Comment by jfparadis** [comment]
@warner, good catch: it hasn't' shown up one in the thousand test we run. 

@erights, great idea. I'll setup a PR.

**Comment by jfparadis** [comment]
I just found that the popular `stack-utils` expects a mutable `Error.prepareStackTrace`, and a callable `Error.captureStackTrace`:

```js
StackUtils.prototype.capture = function (limit, fn) {
  if (typeof limit === 'function') {
    fn = limit;
    limit = Infinity;
  }
  if (!fn) {
    fn = this.capture;
  }
  var prepBefore = Error.prepareStackTrace;
  var limitBefore = Error.stackTraceLimit;
  var wrapCallSite = this._wrapCallSite;

  Error.prepareStackTrace = function (obj, site) {
    if (wrapCallSite) {
      return site.map(wrapCallSite);
    }
    return site;
  };

  if (limit) {
    Error.stackTraceLimit = limit;
  }

  var obj = {};
  Error.captureStackTrace(obj, fn);
  var stack = obj.stack;
  Error.prepareStackTrace = prepBefore;
  Error.stackTraceLimit = limitBefore;

  return stack;
};
```

**Comment by erights** [comment]
> I just found that the popular stack-utils expects a mutable Error.prepareStackTrace, and a callable Error.captureStackTrace:

What does it do on non-v8 browsers, where none of these exist?

**Comment by jfparadis** [comment]
Package `stack-utils` is for node, and doesn't polyfill the Error API. 

I expect it would only be loaded on browsers under browserify, or at least in tandem with the `error-polyfill` package.

**Comment by michaelfig** [comment]
This one bit me today.  I can tame the globals with metering, and get past lockdown(), but then my code crashes with this error.

Other than that, things are looking good!  Such a simpler model. 🎉

**Comment by erights** [comment]
For the untamed setting, in progress at https://github.com/jfparadis/SES-beta/pull/1

**Comment by warner** [comment]
I'm seeing this in a CI run of agoric-sdk, in https://github.com/Agoric/agoric-sdk/pull/762/checks?check_run_id=533828074#step:18:64 . Some test is failing, and I don't know how, because when `tap` tries to render the error, it tries to assign to `Error.stackTraceLimit` first. I provided `noTameError: true` in my `lockdown()` call, but it seems like we freeze `Error` anyways.

**Comment by warner** [comment]
Adding this to the zoe-alpha project because it's blocking my attempts to land `import-bundle`, which is a blocker for moving swingset to new-ses
