### ISSUE TITLE
some unexpected js behavior i wanted to note

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES-shim#86]
`Reflect.defineProperty` and `Object.defineProperty` seem to differ in behavior slightly

In one case I got an error with `Object.defineProperty` but not `Refelect.defineProperty`
```
TypeError: Cannot redefine property: length
```

Another was that, as far as i know, the only way to transition a non-configurable but writable property descriptor to writable false, is via a `Object.freeze`
```js
{ value: x, configurable: false, writable: true }
```
to
```js
{ value: x, configurable: false, writable: false }
```

**Comment by kriskowal** [comment]
Closing since I don’t see any remaining actionable work. Please reopen and clarify otherwise.
