### ISSUE TITLE
what commitments of proxies do you rely on?

### ISSUE THREAD

**Issue by dominictarr** [Agoric/SES-shim#88]
I am trying to grok how SES works, so am reading all the code.
A comment in the source of this module says "we rely upon certain commitments of Object.freeze and proxies here get stable/immutable outbound links before a Proxy has a chance to do something sneaky" then the next line `getPrototypeOf` is used

https://github.com/Agoric/make-hardener/blob/master/src/index.js#L107-L111

But I see that [Proxies can trap calls to getPrototypeOf](https://devdocs.io/javascript/global_objects/proxy/handler/getprototypeof) by "commitments" is it meant that there are certain things that code using a proxy just shouldn't do? it seems like a module exporting a proxy could easily interfer with hardening?

I also notice that proxy is in the Agoric/harden whitelist, https://github.com/Agoric/harden/blob/master/src/whitelist.js#L821 and indeed within the TinySES set

https://raw.githubusercontent.com/Agoric/Jessie/master/docs/jessie.png

Maybe it's difficult to use a proxy to attack other code, but it seems like it could definitely be used to make your own code vulnerable?

**Comment by kriskowal** [comment]
Good to see you here @dominictarr! I’m closing this issue since your question appears answered. I look forward to seeing you around.
