### ISSUE TITLE
Breaking change: make mandatory argument a mutable WeakSet

### ISSUE THREAD

**Issue by michaelfig** [Agoric/SES-shim#90]
If Agoric/make-hardener#35 is merged, then we have the following:

@erights wrote, in Agoric/make-hardener#35 ([comment](/Agoric/make-hardener/pull/35#discussion_r274212361)):
> I don't like the redundancy between initialFringe and opt.fringeSet. Perhaps it would be better if the one mandatory argument were a set instead of an iterable?
>
> Note that any such change would be a compat break, which we now need to worry about. So we need to discuss this.

Changing the API would obviate the need for options.fringeSet.

**Comment by kriskowal** [comment]
Closing as per #412 make-hardener will not be public API going forward.
