### ISSUE TITLE
merge whitelist with SES

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#95]
@erights is concerned about potential divergence between the SES whitelist (which defines what properties of the global objects are retained or deleted) and the Harden "fringelist" (which defines the border of what `harden()` will complain about not already being frozen). He suggested that we should find a way to merge these two lists.

SES defines a `whitelist.js` that is effectively a JSON object that maps object names (hierarchically accessed from a global, e.g. `Number`, `Number.isInteger`, `Number.prototype`, and `Number.prototype.toFixed`) to permission values (basically: true, false, or Jessie-only). The idea is that SES deletes properties of standard javascript that are known to be unsafe (they break confinement or behave nondeterministically). SES then freezes everything that's left, and the result is an object-capability -safe environment. The whitelist includes a section named `anonIntrinsics` which lists permission values for the so-called "anonymous intrinsics", which are built-in functions that cannot be reached with simple property/prototype lookup from the global object (e.g. an `AsyncFunction` which is the constructor of the prototype of a function defined as `async function foo()`).

 SES has a function named `removeProperties` that turns this whitelist document into a "white table" (a `WeakMap` that maps from objects into true/false). It then walks the global object (a recursive traversal of all properties) and deletes any children that aren't in the whitetable. Later, it freezes everything reachable by either property lookup or prototype climbing, using both the global object and the `anonIntrinsics` as starting points. The goal is for everything reachable (by names, prototypes, or syntax) to be frozen, and for the unsafe things to be deleted entirely.

The purpose of a standalone `harden()` function is to make life easier for developers who are building code for a SES environment. This code is going to use `harden()`, but it's impractical to run all your unit tests under SES. The two immediate problems are the need to stringify everything that gets evaluated under SES, and the confusion of stack traces (line numbers in particular) when the code goes through `eval`. So we want developers to write small modules (that include calls to `harden()`) that can be unit-tested separately, outside of SES, even though integration tests and the final application will run inside a SES realm.

These small modules should not need to sense which environment they're in or behave differently. So they should be able to say `const harden = require('harden');`. Outside SES, `harden()` is not providing significant security, because the primordials won't be frozen and an attacker could just redefine `Number` or `Array` to get control. But we want developers to use `harden()` correctly, so we want it to throw errors in the same ways: if they mutate a property on an object that was supposed to be frozen, we want them to get an error in their unit tests where it's easier to debug. And if they `harden()` an object before hardening its prototype, they should get an error too. (we thought about having `harden()` just freeze the prototypes too, basically freezing the entire world, but that seems too drastic for a test environment).

So we want the "fringe" of the standalone `harden()` to match the frozen properties of the SES environment. (The fringe should not include the removed properties: if someone creates an object with a prototype pointing at `Math.rand`, and they try to `harden()` it, then the standalone harden will throw an error because `Math.rand` is not in the fringe; in the SES environment you couldn't have assigned that prototype in the first place because `Math.rand` is missing entirely, so the two cases will both produce errors albeit of different forms).

One approach we're considering is to have `Harden` depend upon `SES`, and have `SES` export a `harden` function that is built around the same list it uses for the in-SES version. This increases the dependency load of code that uses `Harden`, but we don't expect that much code will exist that uses `Harden` but not also `SES`. (One counter-argument is the upcoming RealmsCompartment, which is a lighter-weight non-nested single-realm form of SES, which will also want to expose a `harden()` function.. we may need to build one out of the other to keep things tidy).

We considering having SES export a table of the objects that it has frozen, but that seems inelegant. In addition, it provides a table of objects that the creator of the SES environment might have wanted to withhold from the confined code (who knows, maybe you don't like `Math`, and you want to prevent the confined code from using it at all; if the `SES` object is defined to offer a `SES.frozenObjects` list, then the confined code could just look through that for the denied object).

**Comment by kriskowal** [comment]
Consensus going forward is that the `harden` that `ses` adds to the globalThis is now the only `harden` and that `@agoric/harden` and `@agoric/make-hardener` are deprecated. That deprecation is tracking at #41.

Please reopen if I missed further untracked work items.
